version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'db-postgres'
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_DB=buysell_angular'

  back:
    image: 'tymuro/buysell-spring:1.1'
    container_name: 'buysell-api'
    ports:
      - 80:8080