apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-crud-deployment
spec:
  selector:
    matchLabels:
      app: spring-k8s-postgres
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-k8s-postgres
    spec:
      containers:
        - name: spring-k8s-deployment
          image: spring-k8s-deployment:1.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: dbName
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: spring-crud-svc
spec:
  selector:
    app: spring-k8s-postgres
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort