
spring:
  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  main:
    allow-circular-references: true

jwt:
  secret: SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
  lifetime: 30m
#server:
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: classpath:ssl/buysell_ssl_buysellca_.pfx
#    key-store-password: TymurOvcharenko1669
